### ISSUE TITLE
Blue Seals give moons with Bunco installed

### ISSUE THREAD

**Issue by jumbocarrot0** [survovoaneend/All-In-Jest#4]
The patch below does not work when Bunco is installed. Bunco modifies the same function, causing All In Jest's pattern to not match.
At a glance, I think this can be simplified. If the pattern is just `if v.config.hand_type == G.GAME.last_hand_played then`, then the payload can just be `if v.config.hand_type == G.GAME.last_hand_played and not v.config.moon then` (or better yet, use regex and wildcards to match anything other mods are adding).

I also see a couple other changes in the patch as well. Those are probably best to split into multiple patches.

```toml

# blue seals can work with moons
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
function Card:get_end_of_round_effect(context)
    local ret = {}
    local h_dollars = self:get_h_dollars()
    if h_dollars ~= 0 then
        ret.h_dollars = h_dollars
        ret.card = self
    end
    if self.seal == 'Blue' and #G.consumeables.cards + G.GAME.consumeable_buffer < G.consumeables.config.card_limit and not self.ability.extra_enhancement then
        local card_type = 'Planet'
        G.GAME.consumeable_buffer = G.GAME.consumeable_buffer + 1
        G.E_MANAGER:add_event(Event({
            trigger = 'before',
            delay = 0.0,
            func = (function()
                if G.GAME.last_hand_played then
                    local _planet = 0
                    for k, v in pairs(G.P_CENTER_POOLS.Planet) do
                        if v.config.hand_type == G.GAME.last_hand_played then
                            _planet = v.key
                        end
                    end
                    local card = create_card(card_type,G.consumeables, nil, nil, nil, nil, _planet, 'blusl')
                    card:add_to_deck()
                    G.consumeables:emplace(card)
                    G.GAME.consumeable_buffer = 0
                end
                return true
            end)}))
        card_eval_status_text(self, 'extra', nil, nil, nil, {message = localize('k_plus_planet'), colour = G.C.SECONDARY_SET.Planet})
        ret.effect = true
    end
    return ret
end
'''
position = "at"
match_indent = false
payload = '''

function Card:get_end_of_round_effect(context)
    if self.debuff then return {} end
    local ret = {}
    if self.ability.h_dollars > 0 then
        ret.h_dollars = self.ability.h_dollars
        ret.card = self
    end
    if self.seal == 'Blue' and #G.consumeables.cards + G.GAME.consumeable_buffer < G.consumeables.config.card_limit then
        local card_type = 'Planet'
        G.GAME.consumeable_buffer = G.GAME.consumeable_buffer + 1
        G.E_MANAGER:add_event(Event({
            trigger = 'before',
            delay = 0.0,
            func = (function()
                if G.GAME.last_hand_played then
                    local _planet = 0
                    for k, v in pairs(G.P_CENTER_POOLS.Planet) do
                        if v.config.hand_type == G.GAME.last_hand_played and not v.config.moon then
                            _planet = v.key
                        end
                    end
                    local card = create_card(card_type,G.consumeables, nil, nil, nil, nil, _planet, 'blusl')
                    card:add_to_deck()
                    G.consumeables:emplace(card)
                    G.GAME.consumeable_buffer = 0
                end
                return true
            end)}))
        card_eval_status_text(self, 'extra', nil, nil, nil, {message = localize('k_plus_planet'), colour = G.C.SECONDARY_SET.Planet})
        ret.effect = true
    end
    return ret
end
'''
```

EDIT: Should also mention, this is the Bunco patch that breaks this:

```toml

# Deal hand crash fix for Blue Seal
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = "local card = create_card(card_type,G.consumeables, nil, nil, nil, nil, _planet, 'blusl')"
position = 'before'
match_indent = true
payload = '''

if _planet == 0 then
    _planet = 'c_pluto'
end

'''

```

**Comment by jumbocarrot0** [comment]
Quick (untested) example of regex solution to use wildcards:

```toml

# blue seals can work with moons
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''(?<indent>[\t ]*)if v.config.hand_type == G.GAME.last_hand_played (?<post>.*)'''
position = "at"
line_prepend = '$indent'
payload = '''if v.config.hand_type == G.GAME.last_hand_played and not v.config.moon $post'''
```
