### ISSUE TITLE
Loading Beanstalk joker in collection undebuffs all jacks in deck

### ISSUE THREAD

**Issue by jumbocarrot0** [survovoaneend/All-In-Jest#83]
https://github.com/user-attachments/assets/f048aa54-db0c-441a-871f-f4916ffd06f3

Forgot to show in video, but this affects the jacks in the deck but not yet drawn to hand.

**Comment by jumbocarrot0** [comment]
One possible solution would be to add a patch to the set_debuff function like Bunco does:
```toml
# Prevent debuff
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = "function Card:set_debuff(should_debuff)"
position = 'after'
match_indent = true
payload = '''

if self.edition and self.edition.bunc_fluorescent then
    if self.debuff then
        self.debuff = false
        if self.area == G.jokers then self:add_to_deck(true) end
    end
    return
end

'''
```
